using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Demo.Generator;

[Generator]
public class ToJsonGenerator : IIncrementalGenerator
{
    private const string ToJsonSerializerAttribute =
        """
        using System;

        namespace Demo.Generator;

        [AttributeUsage(AttributeTargets.Class)]
        public class ToJsonSerializerAttribute : Attribute
        {
            public bool Minified { get; }
            
            public ToJsonSerializerAttribute(bool minified = false) 
            {
                Minified = minified;
            }
        }
        """;

    private const string PartialClassTemplate =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by ToJsonGenerator{{generatedAt}}.
        // </auto-generated>
        //------------------------------------------------------------------------------
        using System.Text;
        using System.Text.Json;
        using System.Text.Encodings.Web;

        namespace {{namespace}};

        {{classAccessibility}} partial class {{className}}
        {
            public string ToJson()
            {
                var builder = new StringBuilder();
            
                builder.{{appendLine}}("{");
        {{properties}}
                builder.Append('}');
            
                return builder.ToString();
            }
        }
        """;

    private const string PropertyTemplate =
        """
                builder.{{appendLine}}($"{{space}}{{space}}\"{{name}}\":{{space}}\"{JsonEncodedText.Encode({{name}}, JavaScriptEncoder.Default)}\",");
        """;


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // output static files like attributes (only called once when the source generator is first starting up)
        context.RegisterPostInitializationOutput(ctx => ctx
            .AddSource("ToJsonSerializerAttribute.g.cs", SourceText.From(ToJsonSerializerAttribute, Encoding.UTF8)));

        // var provider = context.SyntaxProvider
        //     .CreateSyntaxProvider(Predicate, Transform)
        //     .Where(x => x is not null);

        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName("Demo.Generator.ToJsonSerializerAttribute", Predicate, Transform);

        // for files that will generate dynamically, we need to call a different method called register source output
        context.RegisterSourceOutput(provider, Generate);
    }

    /**
     * The Generate() method takes a single ClassInfo instance and is expected to turn it into code, which it then adds
     * to the SourceProductionContext. And this is where that caching mechanism comes into play. If we visit the same
     * node in the future, and it hasn't changed in any meaningful way, then its class info will be the same.
     */
    private void Generate(SourceProductionContext context, ClassInfo classInfo)
    {
        var builder = new StringBuilder();
        foreach (var property in classInfo.Properties)
        {
            builder.AppendLine(PropertyTemplate
                .Replace("{{space}}", classInfo.Minified ? string.Empty : " ")
                .Replace("{{appendLine}}", classInfo.Minified ? "Append" : "AppendLine")
                .Replace("{{name}}", property.Name));
        }

        var properties = builder.ToString(0, builder.Length - 6) + "\");";

        var output = PartialClassTemplate
#if DEBUG
            .Replace("{{generatedAt}}", $" at {DateTime.Now:T}")
#else
            .Replace("{{generatedAt}}", string.Empty)
#endif
            .Replace("{{appendLine}}", classInfo.Minified ? "Append" : "AppendLine")
            .Replace("{{classAccessibility}}", classInfo.Accessibility.ToString()
                .ToLower())
            .Replace("{{namespace}}", classInfo.Namespace)
            .Replace("{{className}}", classInfo.Name)
            .Replace("{{properties}}", properties)
            .Replace("{{space}}", classInfo.Minified ? string.Empty : " ");

        context.AddSource($"{classInfo.Name}.g.cs", output);
    }

    private static ClassInfo Transform(GeneratorAttributeSyntaxContext syntaxContext,
        CancellationToken cancellationToken)
    {
        var attribute = syntaxContext.Attributes.Single();
        var minified = attribute.ConstructorArguments[0].Value as bool? == true;
        var classSymbol = syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.TargetNode);
        var classInfo = new ClassInfo
        {
            Namespace = classSymbol?.ContainingNamespace.ToDisplayString(),
            Name = classSymbol?.Name,
            Accessibility = classSymbol?.DeclaredAccessibility,
            Properties = GetPropertyInfos(classSymbol),
            Minified = minified
        };

        return classInfo;
    }

    private static IEnumerable<PropertyInfo> GetPropertyInfos(ISymbol? classSymbol)
    {
        if (classSymbol is not INamedTypeSymbol namedTypeSymbol)
        {
            return [];
        }

        var properties = namedTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .OrderBy(p => p.Name)
            .Select(p => new PropertyInfo
            {
                Accessibility = p.DeclaredAccessibility,
                Name = p.Name,
            });

        return properties;
    }

    private static bool Predicate(SyntaxNode node, CancellationToken token)
    {
        return true;
    }
}

public record struct ClassInfo
{
    public string? Namespace { get; set; }
    public string? Name { get; set; }
    public Accessibility? Accessibility { get; set; }
    public IEnumerable<PropertyInfo> Properties { get; set; }
    public bool Minified { get; set; }

    public readonly bool Equals(ClassInfo other)
    {
        return Namespace == other.Namespace
               && Minified == other.Minified
               && Name == other.Name
               && Accessibility == other.Accessibility
               && Properties.SequenceEqual(other.Properties);
    }

    public readonly override int GetHashCode()
    {
        unchecked
        {
            var hashCode = (Namespace != null ? Namespace.GetHashCode() : 0);
            hashCode = (hashCode * 397) ^ (Name != null ? Name.GetHashCode() : 0);
            hashCode = (hashCode * 397) ^ Accessibility.GetHashCode();
            hashCode = (hashCode * 397) ^ Minified.GetHashCode();
            hashCode = (hashCode * 397) ^
                       Properties.Aggregate(hashCode, (current, property) => current ^ property.GetHashCode());
            return hashCode;
        }
    }
}

public record struct PropertyInfo
{
    public Accessibility? Accessibility { get; set; }
    public string? Name { get; set; }
}