using System;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Demo.Generator;

[Generator]
public class ToJsonGenerator : IIncrementalGenerator
{
    private const string ToJsonSerializerAttribute =
        """
        using System;

        namespace Demo.Generator;

        [AttributeUsage(AttributeTargets.Class)]
        public class ToJsonSerializerAttribute : Attribute
        {
        }
        """;

    private const string PartialClassTemplate =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by ToJsonGenerator{{generatedAt}}.
        // </auto-generated>
        //------------------------------------------------------------------------------

        namespace {{namespace}};

        {{classAccessibility}} partial class {{className}}
        {
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // output static files like attributes (only called once when the source generator is first starting up)
        context.RegisterPostInitializationOutput(ctx => ctx
            .AddSource("ToJsonSerializerAttribute.g.cs", SourceText.From(ToJsonSerializerAttribute, Encoding.UTF8)));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(x => x is not null);

        // for files that will generate dynamically, we need to call a different method called register source output
        context.RegisterSourceOutput(provider, Generate);
    }

    /**
     * The Generate() method takes a single ClassInfo instance and is expected to turn it into code, which it then adds
     * to the SourceProductionContext. And this is where that caching mechanism comes into play. If we visit the same
     * node in the future, and it hasn't changed in any meaningful way, then its class info will be the same.
     */
    private void Generate(SourceProductionContext context, ClassInfo? classInfo)
    {
        if (classInfo is null)
        {
            return;
        }

        var output = PartialClassTemplate
            .Replace("{{generatedAt}}", $" at {DateTime.Now:s}")
            .Replace("{{classAccessibility}}", classInfo.Value.Accessibility.ToString().ToLower())
            .Replace("{{namespace}}", classInfo.Value.Namespace)
            .Replace("{{className}}", classInfo.Value.Name);

        context.AddSource($"{classInfo.Value.Name}.g.cs", output);
    }

    private static ClassInfo? Transform(GeneratorSyntaxContext syntaxContext, CancellationToken cancellationToken)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)syntaxContext.Node;

        foreach (var attributeList in classDeclarationSyntax.AttributeLists)
        {
            foreach (var attributeSyntax in attributeList.Attributes)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    return null;
                }

                var attributeName = attributeSyntax.Name.ToString();
                if (attributeName != "ToJsonSerializerAttribute" && attributeName != "ToJsonSerializer")
                {
                    continue;
                }

                // Now that we've done some initial filtering, we can transform our class declaration syntax node into its equivalent semantic model for a more in-depth analysis.
                var attributeSymbolInfo = syntaxContext.SemanticModel.GetSymbolInfo(attributeSyntax);

                if (attributeSymbolInfo.Symbol is not IMethodSymbol methodSymbol)
                {
                    continue;
                }

                var attributeSymbol = methodSymbol.ContainingType;

                if (attributeSymbol.ToDisplayString() != "Demo.Generator.ToJsonSerializerAttribute" &&
                    attributeSymbol.ToDisplayString() != "Demo.Generator.ToJsonSerializer")
                {
                    continue;
                }

                var classSymbol = syntaxContext.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax);

                var classInfo = new ClassInfo
                {
                    Namespace = classSymbol?.ContainingNamespace.ToDisplayString(),
                    Name = classSymbol?.Name,
                    Accessibility = classSymbol?.DeclaredAccessibility,
                };

                return classInfo;
            }
        }

        return null;
    }

    private static bool Predicate(SyntaxNode node, CancellationToken token)
    {
        return node is ClassDeclarationSyntax
        {
            AttributeLists.Count: > 0
        };
    }
}

public record struct ClassInfo
{
    public string? Namespace { get; set; }
    public string? Name { get; set; }
    public Accessibility? Accessibility { get; set; }
}