@RiverBooks_Web_HostAddress = https://localhost:7130

GET {{RiverBooks_Web_HostAddress}}/books
Accept: application/json

###

@BookID = 00000000-0000-0000-0000-000000000004
GET {{RiverBooks_Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{RiverBooks_Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json


{
  "id": "00000000-0000-0000-0000-000000000004",
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

###

DELETE {{RiverBooks_Web_HostAddress}}/books/00000000-0000-0000-0000-000000000004
Accept: application/json

###

POST {{RiverBooks_Web_HostAddress}}/books/00000000-0000-0000-0000-000000000004/pricehistory
Accept: application/json
Content-Type: application/json


{
  "id": "00000000-0000-0000-0000-000000000004",
  "newPrice": -9.99
}

###

POST {{RiverBooks_Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "steve@test.com",
  "password": "Pass@word1"
}

###

POST {{RiverBooks_Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "steve@test.com",
  "password": "Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzdGV2ZUB0ZXN0LmNvbSIsImlhdCI6MTc3MTQwNDk0MCwiZXhwIjoxNzcxNDA4NTQwLCJuYmYiOjE3NzE0MDQ5NDB9.PA-XM1M0cUtsEd7vE6JSE2WIFcuMhZUofw7Rkpyrrg4