@RiverBooks_Web_HostAddress = http://localhost:5285

GET {{RiverBooks_Web_HostAddress}}/books
Accept: application/json

###

@BookID = 00000000-0000-0000-0000-000000000001
GET {{RiverBooks_Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###

POST {{RiverBooks_Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json


{
  "id": "00000000-0000-0000-0000-000000000004",
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

###

DELETE {{RiverBooks_Web_HostAddress}}/books/00000000-0000-0000-0000-000000000004
Accept: application/json

###