@RiverBooks_Web_HostAddress = http://localhost:5285

GET {{RiverBooks_Web_HostAddress}}/books
Accept: application/json

###

@BookID = 00000000-0000-0000-0000-000000000001
GET {{RiverBooks_Web_HostAddress}}/books/{{BookID}}
Accept: application/json

###
