services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
    ports:
      - '5433:5432'

