using Demo.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Demo.Tests;

public class VerifyOutput
{
    [Fact]
    public async Task Then_the_expected_output_is_generated()
    {
        var generator = new ToJsonGenerator();
        var syntaxTree = CSharpSyntaxTree.ParseText(GetResourceAsString("Address.cs"));
        var compilation = CSharpCompilation.Create(
            nameof(Then_the_expected_output_is_generated), // assembly name, for tests like this it's arbitrary 
            [syntaxTree],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);
        var result = driver.GetRunResult();
        var output = result.GeneratedTrees.Single(t => t.FilePath.EndsWith("Address.g.cs"))
            .ToString();

        var settings = new VerifySettings();
        settings.UseDirectory("Verify");
        settings.ScrubLinesContaining("This code was generated by ToJsonGenerator");
        await Verify(output, settings);
    }

    private string GetResourceAsString(string resourceName)
    {
        var assembly = typeof(VerifyOutput).Assembly;
        var manifestResourceNames = assembly.GetManifestResourceNames();
        resourceName = manifestResourceNames.Single(x =>
            x.Equals($"Demo.Tests.{resourceName}", StringComparison.OrdinalIgnoreCase));

        using var stream = assembly.GetManifestResourceStream(resourceName) ??
                           throw new InvalidOperationException($"Resource '{resourceName}' not found.");
        using var reader = new StreamReader(stream);

        return reader.ReadToEnd();
    }
}